<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>obj-turborama\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>obj-turborama\</MSBuildProjectExtensionsPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj\**;obj-turborama\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
