<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <AssemblyName>Turborama-Launcher</AssemblyName>
    <RootNamespace>TurboramaBootstrapper</RootNamespace>
    <Version>1.6.2</Version>
    <AssemblyVersion>1.6.2.0</AssemblyVersion>
    <FileVersion>1.6.2.0</FileVersion>
    <InformationalVersion>1.6.2-private-single-exe</InformationalVersion>
    <Product>Turborama</Product>
    <Description>Turborama privado completo com catálogo e downloads</Description>
    <Company>LZ Games</Company>
    <Copyright>Copyright (c) LZ Games</Copyright>
    <ApplicationIcon>turborama-app-icon.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
